version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: >
      bash -c "python manage.py makemigrations &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    command: celery -A dost_index worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - django
      - redis

  pgdb:
    image: postgres
    container_name: pgdb
    env_file: .env

    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
