version: "3.8"

services:
  pgdb:
    image: postgres
    restart: "always"
    container_name: dost-index-database
    env_file: .env
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    container_name: dost-index-redis
    restart: "always"
    env_file: .env
    command: ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - ./volumes/redisdb:/var/lib/redis

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    restart: "always"
    container_name: dost-index-celery
    command: celery --app=apps.todo.config.celery:app worker -E --beat --scheduler django --loglevel=info
    volumes:
      - ./volumes/celery:/usr/src/app
    env_file: .env
    depends_on:
      - pgdb
      - redis

  django:
    build:
      context: .
      dockerfile: django.dockerfile
    container_name: dost-index-web
    restart: "always"
    command: >
      bash -c "
                python manage.py migrate &&
                python manage.py populate &&
                python manage.py runserver 0.0.0.0:8000
              "
    volumes:
      - ./volumes/django/media:/usr/src/app/media
      - ./volumes/django/static:/usr/src/app/static
      - .:/usr/src/app

    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - pgdb
      - redis
      - celery
    links:
      - pgdb
      - redis
      - celery

  
  
volumes:
  pgdata:
  celery:
  django:
  redis:
