# Generated by Django 4.2.10 on 2024-02-28 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Liderlik.', max_length=64, verbose_name='Blok adı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='DOST Mərkəzi #1', max_length=128, verbose_name='Dost mərkəzinin adı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='1', max_length=5, verbose_name='Kod nömrəsi')),
                ('title', models.CharField(default='Hədəfə çatma', max_length=64, verbose_name='Göstərici - KPİ adı')),
                ('maximum', models.PositiveIntegerField(default=100, help_text='Aj üçün mümkün yuxarı sərhədd')),
                ('minimum', models.PositiveIntegerField(default=0, help_text='Aj üçün mümkün aşağı sərhədd')),
                ('Aij_minimum', models.PositiveIntegerField(default=0, help_text='Məlumatın hesablanması üçün lazım olan minimum dəyər')),
                ('Aij_maximum', models.PositiveIntegerField(default=0, help_text='Məlumatın hesablanması üçün lazım olan max dəyər')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='assessment.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Göstərici dəyəri')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='assessment.assessment')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='assessment.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessment.dostcenter'),
        ),
    ]
