# Generated by Django 5.0.2 on 2024-03-04 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_article_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='coefficient',
            field=models.FloatField(default=0, help_text='Əmsal', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_points',
            field=models.FloatField(default=0, help_text='Altmeyarlar üzrə maksimum bal', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assessmentpoint',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)], verbose_name='Göstərici dəyəri'),
        ),
        migrations.AlterField(
            model_name='section',
            name='Aij_maximum',
            field=models.FloatField(default=0, help_text='Məlumatın hesablanması üçün lazım olan max dəyər', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='Aij_minimum',
            field=models.FloatField(default=0, help_text='Məlumatın hesablanması üçün lazım olan minimum dəyər', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='maximum',
            field=models.FloatField(default=0, help_text='Aj üçün mümkün yuxarı sərhədd', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='minimum',
            field=models.FloatField(default=0, help_text='Aj üçün mümkün aşağı sərhədd', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
