# Generated by Django 5.0.2 on 2024-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_section_coefficient_section_sub_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='formula',
            field=models.CharField(choices=[('formula_min_max_min', 'Əmsal * Altmeyar * (Aij - Ajmin)/(Ajmax - Ajmin)'), ('formula_max_min_max', 'Əmsal * Altmeyar * (Aij - Ajmax)/(Ajmin - Ajmax)')], null=True),
        ),
    ]
