# Generated by Django 5.0.3 on 2024-03-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_dostkpiresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostkpiresult',
            name='period_quarter',
            field=models.PositiveIntegerField(default=0, help_text='Dövr rüb', verbose_name='Quarter of the Period'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='period_year',
            field=models.PositiveIntegerField(default=2024, help_text='Dövr il', verbose_name='Year of the Period'),
        ),
    ]
