# Generated by Django 5.0.3 on 2024-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_assessment_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='quarter',
            field=models.CharField(choices=[('1', 'I Rüb'), ('2', 'II Rüb'), ('3', 'III Rüb'), ('4', 'IV Rüb')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='period_quarter',
            field=models.CharField(default='I rüb', help_text='Dövr rüb', verbose_name='Quarter of the Period'),
        ),
        migrations.AlterUniqueTogether(
            name='dostkpiresult',
            unique_together={('dost_center', 'period_year', 'period_quarter')},
        ),
    ]
