# Generated by Django 5.0.3 on 2024-03-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessment_quarter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('quarter', 'center')},
        ),
    ]
