# Generated by Django 5.0.3 on 2024-03-04 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_alter_assessment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='Aij_maximum',
            field=models.FloatField(default=1, help_text='Məlumatın hesablanması üçün lazım olan max dəyər', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='Aij_minimum',
            field=models.FloatField(default=1, help_text='Məlumatın hesablanması üçün lazım olan minimum dəyər', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='coefficient',
            field=models.FloatField(default=1, help_text='Əmsal', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='maximum',
            field=models.FloatField(default=1, help_text='Aj üçün mümkün yuxarı sərhədd', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='minimum',
            field=models.FloatField(default=1, help_text='Aj üçün mümkün aşağı sərhədd', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_points',
            field=models.FloatField(default=1, help_text='Altmeyarlar üzrə maksimum bal', validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
