# Generated by Django 5.0.3 on 2024-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_section_aij_maximum_alter_section_aij_minimum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DostKPIResultExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dost_center', models.CharField(default='Dost Mərkəzi #1', help_text='Dost mərkəzinin adı', max_length=64)),
                ('period_year', models.PositiveIntegerField(default=2024, help_text='Dövr il', verbose_name='Year of the Period')),
                ('period_quarter', models.CharField(default='I rüb', help_text='Dövr rüb', verbose_name='Quarter of the Period')),
                ('requirements_compliance', models.FloatField(default=0, help_text='5.1. Tələblərə görə icra')),
                ('it_infrastructure', models.FloatField(default=0, help_text='5.2. İT infrastruktur')),
                ('communication', models.FloatField(default=0, help_text='5.3. Kommunikasiya')),
                ('back_office_satisfaction', models.FloatField(default=0, help_text='5.4. Arxa ofislərdən məmnunluq')),
            ],
            options={
                'unique_together': {('dost_center', 'period_year', 'period_quarter')},
            },
        ),
    ]
