# Generated by Django 5.0.3 on 2024-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_dostkpiresultexternal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'KPİ Bloku', 'verbose_name_plural': 'KPİ Blokları'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Qiymətləndirmə', 'verbose_name_plural': 'Qiymətləndirmələr'},
        ),
        migrations.AlterModelOptions(
            name='assessmentpoint',
            options={'verbose_name': 'Göstərici', 'verbose_name_plural': 'Göstəricilər'},
        ),
        migrations.AlterModelOptions(
            name='dostcenter',
            options={'verbose_name': 'Dost Mərkəzi', 'verbose_name_plural': 'Dost Mərkəzləri'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresult',
            options={'verbose_name': 'Qiymətləndirmə Nəticəsi', 'verbose_name_plural': 'Qiymətləndirmə Nəticələri'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresultexternal',
            options={'verbose_name': 'Əlavə Qiymətləndirmə Nəticəsi', 'verbose_name_plural': 'Əlavə Qiymətləndirmə Nəticələri'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'KPİ Göstərici', 'verbose_name_plural': 'KPİ Göstəriciləri'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, max_length=4),
        ),
    ]
