# Generated by Django 5.0.3 on 2024-03-28 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_alter_assessment_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Qiymətləndirmə Anketi', 'verbose_name_plural': 'Qiymətləndirmə Anketləri'},
        ),
        migrations.AlterModelOptions(
            name='dostcenter',
            options={'verbose_name': 'DOST Mərkəzi', 'verbose_name_plural': 'DOST Mərkəzləri'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresult',
            options={'verbose_name': 'Qiymətləndirmə Nəticəsi (Daxili)', 'verbose_name_plural': 'Qiymətləndirmə Nəticələri (Daxili)'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresultexternal',
            options={'verbose_name': 'Qiymətləndirmə Nəticəsi (Xarici)', 'verbose_name_plural': 'Qiymətləndirmə Nəticələri (Xarici)'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='Aij_maximum',
        ),
        migrations.RemoveField(
            model_name='section',
            name='Aij_minimum',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(limit_value=1990), django.core.validators.MaxValueValidator(limit_value=2100)]),
        ),
    ]
