# Generated by Django 5.0.3 on 2024-03-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_assessment_options_alter_dostcenter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['article__code', 'code'], 'verbose_name': 'KPİ Göstərici', 'verbose_name_plural': 'KPİ Göstəriciləri'},
        ),
    ]
