# Generated by Django 5.0.3 on 2024-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_dostkpiresult_total_dostkpiresult_total_article_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['code'], 'verbose_name': 'KPİ Bloku', 'verbose_name_plural': 'KPİ Blokları'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresult',
            options={'ordering': ['dost_center', 'period_year', 'period_quarter'], 'verbose_name': 'Qiymətləndirmə Nəticəsi (Daxili)', 'verbose_name_plural': 'Qiymətləndirmə Nəticələri (Daxili)'},
        ),
        migrations.AlterModelOptions(
            name='dostkpiresultexternal',
            options={'ordering': ['dost_center', 'period_year', 'period_quarter'], 'verbose_name': 'Qiymətləndirmə Nəticəsi (Xarici)', 'verbose_name_plural': 'Qiymətləndirmə Nəticələri (Xarici)'},
        ),
        migrations.AddField(
            model_name='dostkpiresult',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dostkpiresult',
            name='total_article_unnamed',
            field=models.FloatField(blank=True, default=0, verbose_name='X. Yekun - Yeni maddələr'),
        ),
        migrations.AddField(
            model_name='dostkpiresultexternal',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='administrative_violations',
            field=models.FloatField(default=0, verbose_name='1.2. İnzibati qayda pozuntuları'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='average_service_time',
            field=models.FloatField(default=0, verbose_name='2.3. Orta xidmət müddəti'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='average_waiting_time',
            field=models.FloatField(default=0, verbose_name='2.2. Orta gözləmə müddəti'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='back_office_denials',
            field=models.FloatField(default=0, verbose_name='3.3. Arxa ofis imtinaları'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='citizen_reception',
            field=models.FloatField(default=0, verbose_name='1.4. Vətəndaş qəbulu'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='citizen_satisfaction',
            field=models.FloatField(default=0, verbose_name='2.1. Vətəndaş məmnunluğu'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='complaints_answered',
            field=models.FloatField(default=0, verbose_name='2.6. Cavablandırılan şikayətlər'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='compliance_with_normative_documents',
            field=models.FloatField(default=0, verbose_name='3.1. Xidmət proseslərinin normativ sənədlərə uyğunluğu'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='corporate_culture',
            field=models.FloatField(default=0, verbose_name='1.5. Korporativ mədəniyyət'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='delayed_documents',
            field=models.FloatField(default=0, verbose_name='3.4. Gecikdirilmiş sənədlər'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='dost_center',
            field=models.CharField(default='Dost Mərkəzi #1', max_length=64, verbose_name='Dost mərkəzinin adı'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='employee_satisfaction',
            field=models.FloatField(default=0, verbose_name='4.2. İşçilərin məmnunluğu'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='employee_satisfaction_with_leaders',
            field=models.FloatField(default=0, verbose_name='1.3. İşçilərin rəhblərdən məmnunluğu'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='employee_turnover',
            field=models.FloatField(default=0, verbose_name='4.1. İşçi dövriyyəsi'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='exam_results',
            field=models.FloatField(default=0, verbose_name='4.3. İmtahan nəticələri'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='on_site_response',
            field=models.FloatField(default=0, verbose_name='2.7. Yerində cavablandırma'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='period_quarter',
            field=models.CharField(default='I rüb', verbose_name='Dövr rüb'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='period_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Dövr il'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='repeat_visits',
            field=models.FloatField(default=0, verbose_name='3.2. Təkrar müraciət'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='resilience_to_risk',
            field=models.FloatField(default=0, verbose_name='3.6. Riskə dayanıqlılıq'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='sa_assessment',
            field=models.FloatField(default=0, verbose_name='4.4. SA qiymətləndirilməsi'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='satisfaction_with_essx',
            field=models.FloatField(default=0, verbose_name='2.4. ESSX-dən məmnunluq'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='substantial_complaints',
            field=models.FloatField(default=0, verbose_name='2.5. Əsaslı şikayətlər'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='target_achievement',
            field=models.FloatField(default=0, verbose_name='1.1. Hədəfə çatma'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='total',
            field=models.FloatField(blank=True, default=0, verbose_name='Yekun'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='total_article_1',
            field=models.FloatField(blank=True, default=0, verbose_name='1. Yekun - Liderlik'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='total_article_2',
            field=models.FloatField(blank=True, default=0, verbose_name='2. Yekun - Vətəndaşlar üçün nəticələr'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='total_article_3',
            field=models.FloatField(blank=True, default=0, verbose_name='3. Yekun - Proseslər üzrə nəticələr'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='total_article_4',
            field=models.FloatField(blank=True, default=0, verbose_name='4. Yekun - İşçilər üçün nəticələr'),
        ),
        migrations.AlterField(
            model_name='dostkpiresult',
            name='volunteer_satisfaction',
            field=models.FloatField(default=0, verbose_name='3.5. Könüllülərdən məmnunluq'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='back_office_satisfaction',
            field=models.FloatField(default=0, verbose_name='5.4. Arxa ofislərdən məmnunluq'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='communication',
            field=models.FloatField(default=0, verbose_name='5.3. Kommunikasiya'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='dost_center',
            field=models.CharField(default='Dost Mərkəzi #1', max_length=64, verbose_name='Dost mərkəzinin adı'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='it_infrastructure',
            field=models.FloatField(default=0, verbose_name='5.2. İT infrastruktur'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='period_quarter',
            field=models.CharField(default='I rüb', verbose_name='Dövr rüb'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='period_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Dövr il'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='requirements_compliance',
            field=models.FloatField(default=0, verbose_name='5.1. Tələblərə görə icra'),
        ),
        migrations.AlterField(
            model_name='dostkpiresultexternal',
            name='total',
            field=models.FloatField(blank=True, default=0, verbose_name='Yekun'),
        ),
    ]
