# Generated by Django 5.0.3 on 2024-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_alter_article_options_alter_dostkpiresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentpoint',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
