# Generated by Django 5.0.3 on 2024-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_assessmentpoint_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
