# Generated by Django 5.0.3 on 2024-04-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_section_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentpoint',
            name='external',
        ),
    ]
